apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: org-pods-applicationset
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/avivlapid/argocd-example.git
      revision: HEAD
      files:
      - path: "organizations.yaml"
  template:
    metadata:
      name: 'org-{{organization}}'
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: https://github.com/avivlapid/argocd-example.git
        targetRevision: HEAD
        path: dummy-helm-chart
        helm:
          values: |
            # Empty pod for organization: {{organization}}
            deployment:
              name: empty-pod-{{organization}}
              replicaCount: 1
              image:
                repository: busybox
                tag: "1.35"
                pullPolicy: IfNotPresent
              command: ["sleep", "3600"]
              env:
                - name: ORGANIZATION
                  value: "{{organization}}"
                - name: ORG_DESCRIPTION
                  value: "{{description}}"
                - name: POD_PURPOSE
                  value: "empty-pod-for-org"
              resources:
                limits:
                  cpu: 200m
                  memory: 256Mi
                requests:
                  cpu: 100m
                  memory: 128Mi
            service:
              enabled: false
            ingress:
              enabled: false
      destination:
        server: https://kubernetes.default.svc
        namespace: 'org-{{organization}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
          - PruneLast=true
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
      revisionHistoryLimit: 5 