apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: org-pods-single-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/avivlapid/argocd-example.git
    targetRevision: HEAD
    path: dummy-helm-chart
    helm:
      valueFiles:
        - "../organizations.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: 'org-pods'
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 5 