# Default values for dummy-website
replicaCount: 2

image:
  repository: nginx
  tag: latest
  pullPolicy: Always

# Configurable message to show GitOps changes
website:
  title: "GitOps Test Website - UPDATED!"
  message: "Version 3.0 - GitOps is working! 🚀"
  backgroundColor: "#e6ffe6"
  textColor: "#2d5a2d"

service:
  type: ClusterIP
  port: 80

# Environment info
environment: "local"
deployment:
  timestamp: "2025-06-22T12:15:00Z"
  version: "v2.0.0" 
