apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dummy-helm-chart.fullname" . }}
  labels:
    {{- include "dummy-helm-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      {{- include "dummy-helm-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        # Force restart when config changes
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        {{- include "dummy-helm-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}"
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
          command: {{ .Values.deployment.command | toJson }}
          {{- if .Values.deployment.env }}
          env:
            {{- toYaml .Values.deployment.env | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.deployment.resources | nindent 12 }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - name: html-content
              mountPath: /usr/share/nginx/html
              readOnly: true
      volumes:
        - name: html-content
          configMap:
            name: {{ include "dummy-helm-chart.fullname" . }}-html
      restartPolicy: Always 