apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dummy-website.fullname" . }}
  labels:
    {{- include "dummy-website.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "dummy-website.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        # Force restart when config changes
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        {{- include "dummy-website.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - name: html-content
              mountPath: /usr/share/nginx/html
              readOnly: true
          env:
            - name: ENVIRONMENT
              value: {{ .Values.environment }}
            - name: DEPLOYMENT_VERSION
              value: {{ .Values.deployment.version }}
      volumes:
        - name: html-content
          configMap:
            name: {{ include "dummy-website.fullname" . }}-html 