{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dummy-helm-chart.fullname" . }}
  labels:
    {{- include "dummy-helm-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.port | default 80 }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "dummy-helm-chart.selectorLabels" . | nindent 4 }}
{{- end }} 